### ISSUE TITLE
Missing "renderType" in TCA of field "[tt_content][tx_templavoila_flex]".

### ISSUE THREAD

**Issue by sytura** [alexanderschnitzler/templavoila#9] opened 2017-05-30 16:44 UTC
| Q                    | A
| -------------------- | -----
| Bug report?          | yes 
| Feature request?     | no
| PHP version          | 7.0.10
| TYPO3 version        | 7.6.18
| TemplaVoilà version  | 7.6.6 

### Actual behaviour

When a FCE is opened in the backend, this error message is shown:

> Missing "renderType" in TCA of field  "[tt_content][tx_templavoila_flex]".

For other FCE I got the message:
> Broken data structure on field name tx_templavoila_flex. section without type or vice versa is not allowed

All FCEs worked well in TYPO3 6.2 with templavola 1.9.2

No problems in the frontend. The output works well, but it is not possible to edit any FCE

Cheers
Roland

**Comment by alexanderschnitzler** [comment] 2017-06-02 10:12
Regarding the renderType, please have a look at the core documentation:
https://docs.typo3.org/typo3cms/TCAReference/7.6/Reference/Columns/Select/Index.html#rendertype

You need to specify how your field (input, select, whatever) should be rendered.

The latter is a duplicate of #4.
No real fix available as of now but you can make your form editable again. Please browse the comments in #4 for that.

Thanks :)
Alex

**Closed as completed by alexanderschnitzler** 2017-06-02 10:12 UTC
